spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1/

logging:
  file:
    name: /app/logs/log.log

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
    crossOrigin: ${CROSS_ORIGIN}